version: '3'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:./var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  web:
    build: .
    image: 'wolverkz/testapi'
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
  rabbitmq:
    image: 'rabbitmq:3.11-management'
    ports:
      - '15672:15672'
      - '5672:5672'
  celery:
    build: .
    image: 'wolverkz/testapi'
    command: celery -A newsweb worker --loglevel=INFO
    volumes:
      - .:/code
    depends_on:
      - db
      - rabbitmq

volumes:
  postgres_data: