version: '3'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=newsweb
      - POSTGRES_PASSWORD=Portal1911sp
    ports:
      - "5432:5432"
    networks:
      djangonetwork:
  web:
    build: .
    image: 'wolverkz/testapi'
    command: python3 newsweb/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
    networks:
      djangonetwork:
  rabbitmq:
    image: 'rabbitmq:3.11-management'
    ports:
      - '15672:15672'
      - '5672:5672'
    networks:
      djangonetwork:
  celery:
    build: .
    image: 'wolverkz/testapi'
    command: celery -A newsweb.newsweb worker --loglevel=INFO
    volumes:
      - .:/code
    depends_on:
      - db
      - rabbitmq
    networks:
      djangonetwork:

volumes:
  postgres_data:

networks:
  djangonetwork:
    driver: bridge