version: '3'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db
    ports:
      - "5432:5432"
    networks:
      djangonetwork:
  web:
    build: ..
    image: 'wolverkz/newsweb:v1'
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - CELERY_RESULT_BACKEND=rpc://
    depends_on:
      - db
      - rabbitmq
    networks:
      djangonetwork:
  rabbitmq:
    image: 'rabbitmq:3.11-management'
    ports:
      - '15672:15672'
      - '5672:5672'
    networks:
      djangonetwork:
  celery:
    build: ..
    image: 'wolverkz/newsweb:v1'
    command: celery -A core worker --loglevel=INFO
    volumes:
      - .:/usr/src/app
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - CELERY_RESULT_BACKEND=rpc://
    depends_on:
      - web
      - db
      - rabbitmq
    networks:
      djangonetwork:

volumes:
  postgres_data:

networks:
  djangonetwork:
    driver: bridge